### ISSUE TITLE
Request to add contributors list to README file.

### ISSUE THREAD

**Issue by Pandz18** [ozamed/Python-Scripts#40]

**Comment by ozamed** [comment]
@Pandz18  Request accepted, i will add soon!

**Comment by Pandz18** [comment]
> @Pandz18 Request accepted, i will add soon!
Awesome , If you can't find the time to do so , I can do it for you

**Comment by ozamed** [comment]
That will be awesome @Pandz18

**Comment by Pandz18** [comment]
awesome , I'll do it right away
